export enum PageEnum {
  Home = "Home",
  Design = "Design",
  DesignEdit = "DesignEdit",
  DesignRoadList = "DesignRoadList",
  Doc = "Doc",
  Authorize = "Authorize",
  Contact = "Contact",
  Login = "Login",
  SignIn = "SignIn",
  UserCenter = "UserCenter",
  // Settings = "Settings",
  BasicInfo = "BasicInfo",
  ResetPwd = "ResetPwd",
  ActivateCode = "ActivateCode",
  Map = "Map",
  Suggestion = "Suggestion",
}
