export const notOpacityClass = [
  "content",
  "content-menu-item",
  "content-menu-item content-menu-item-active",
  "content-main",
  "ant-spin-nested-loading",
  "ant-spin-container",
  "basic-main",
  "gradient-horizontal-a rect",
  "gradient-horizontal-b rect",
  "gradient-horizontal-c rect",
  "gradient-horizontal-d rect",
  "gradient-horizontal-e rect",
  "gradient-horizontal-f rect",
  "gradient-text",
  "gradient-text-1",
  "gradient-text-dec",
  "gradient-text-0",
  "fold",
];
